=== msi-cxb/csharp_DotNet8_ODBC/data/webbedData/employee.dtd
<!ELEMENT company (employee+)>
<!ELEMENT employee (username,password,frstname,lastname,gender,email,posion,salary,contact)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT frstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT posion (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT contact (#PCDATA)>

=== msi-cxb/csharp_DotNet8_ODBC/data/webbedData/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" hre="employee.xsl"?>
<!DOCTYPE company SYSTEM "employee.dtd">
<company>
    <employee>
        <username>Akash123</username>
        <password>akash123</password>
        <frstname>Akash</frstname>
        <lastname>Mete</lastname>
        <gender>Male</gender>
        <email>akashmete129@gmail.com</email>
        <position>Software Developer</position>
        <salary>9.5lpa</salary>
        <contact>+91 7051794388</contact>
    </employee>
    <employee>
        <username>AlexWest</username>
        <password>alex123</password>
        <frstname>Alex</frstname>
        <lastname>West</lastname>
        <gender>Female</gender>
        <email>alex123@gmail.com</email>
        <position>Software Developer</position>
        <salary>8.5lpa</salary>
        <contact>+91 9335784511</contact>
    </employee>
    <employee>
        <username>BarryAllen</username>
        <password>barry123</password>
        <frstname>Barry</frstname>
        <lastname>Allen</lastname>
        <gender>Male</gender>
        <email>barryallen@gmail.com</email>
        <position>Frontend Developer</position>
        <salary>7.5lpa</salary>
        <contact>+91 7834918230</contact>
    </employee>
    <employee>
        <username>JohnDoe</username>
        <password>johndoe123</password>
        <frstname>John</frstname>
        <lastname>Doe</lastname>
        <gender>Male</gender>
        <email>johndoe@example.com</email>
        <position>Marketing Manager</position>
        <salary>12lpa</salary>
        <contact>+91 9934671209</contact>
    </employee>
    <employee>
        <username>JaneSmith</username>
        <password>janesmith456</password>
        <frstname>Jane</frstname>
        <lastname>Smith</lastname>
        <gender>Female</gender>
        <email>janesmith@example.com</email>
        <position>Human Resources Manager</position>
        <salary>10lpa</salary>
        <contact>+91 9091293801</contact>
    </employee>
    <employee>
        <username>BobJohnson</username>
        <password>bob123</password>
        <frstname>Bob</frstname>
        <lastname>Johnson</lastname>
        <gender>Male</gender>
        <email>bob.johnson@example.com</email>
        <position>Software Engineer</position>
        <salary>9lpa</salary>
        <contact>+91 7722012983</contact>
    </employee>
</company>
